GAME_TICK: float = 0.2
UP = "\x1b[1A"
DOWN = "\x1b[1B"
LEFT = "\x1b[1C"
RIGHT = "\x1b[1D"
CLR = "\x1b[0K"
TOP = "\x1b[0;0H"
CO2_BUDGET: int = 100000  # Jos pelaaja päästää enemmän co2 kuin tämä luku häviät pelin
SECURITY_BASE: int = 2
AUTOSAVE_DELAY: int = 5
AIRPORT_MENU_TABS = ["Inventory", "Shop"]
